node_exporter_image: "prom/node-exporter:v1.3.1"
node_exporter_container_name: node-exporter
node_exporter_port: 9100
redis_port: 6379


docker_dir: /opt/docker
docker_dir_mode: '0755'
docker_users:
      - docker_user
docker_files_owner: docker_user
docker_files_mode: '0755'
docker_group: docker

ansible_ssh_user: sa_101994008222971342723

