---
# Postgres
postgres_host: "YOUR_POSTGRES_HOST"
postgres_login_user: "YOUR_POSTGRES_USER"
postgres_login_password: "YOUR_POSTGRES_PASSWORD"
postgres_port: 5432


postgres_admin_user: "YOUR_ADMIN_USER"
postgres_admin_password: "YOUR_ADMIN_PASSWORD"

postgres_schedule_database_name: schedule

postgres_restore_dump: true
postgres_initial_data_dest: "./files/initial_data.sql"
