---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
      - name: google.cloud
      - name: azure.azcollection
      - name: ovirt.ovirt
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.utils
      - name: community.postgresql
      - name: community.hashi_vault
      - name: community.mongodb
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    postgresql-libs
    postgresql
    libpq
    python3-psycopg2
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pyOpenSSL
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    google-auth
    requests
    psycopg2-binary
    jmespath
    hvac
    kubernetes-validate
    
    packaging
    requests[security]
    xmltodict
    msgraph-sdk==1.0.0

    azure-cli-core==2.34.0
    azure-common==1.1.11
    azure-identity==1.14.0
    azure-mgmt-authorization==2.0.0
    azure-mgmt-apimanagement==3.0.0
    azure-mgmt-batch==16.2.0
    azure-mgmt-cdn==11.0.0
    azure-mgmt-compute==26.1.0
    azure-mgmt-containerinstance==9.0.0
    azure-mgmt-core==1.3.0
    azure-mgmt-containerregistry==9.1.0
    azure-containerregistry==1.1.0
    azure-mgmt-containerservice==20.0.0
    azure-mgmt-datalake-store==1.0.0
    azure-mgmt-datafactory==2.0.0
    azure-mgmt-dns==8.0.0
    azure-mgmt-marketplaceordering==1.1.0
    azure-mgmt-monitor==3.0.0
    azure-mgmt-managedservices==6.0.0
    azure-mgmt-managementgroups==1.0.0
    azure-mgmt-network==19.1.0
    azure-mgmt-nspkg==2.0.0
    azure-mgmt-privatedns==1.0.0
    azure-mgmt-redis==13.0.0
    azure-mgmt-resource==21.1.0
    azure-mgmt-rdbms==10.0.0
    azure-mgmt-search==8.0.0
    azure-mgmt-servicebus==7.1.0
    azure-mgmt-sql==3.0.1
    azure-mgmt-storage==19.0.0
    azure-mgmt-trafficmanager==1.0.0b1
    azure-mgmt-web==6.1.0
    azure-nspkg==2.0.0
    azure-storage-blob==12.11.0
    azure-core==1.28.0
    azure-keyvault==4.2.0
    azure-mgmt-keyvault==10.0.0
    azure-mgmt-cosmosdb==6.4.0
    azure-mgmt-hdinsight==9.0.0
    azure-mgmt-devtestlabs==9.0.0
    azure-mgmt-loganalytics==12.0.0
    azure-mgmt-automation==1.0.0
    azure-mgmt-iothub==2.2.0
    azure-iot-hub==2.6.1
    azure-mgmt-recoveryservices==2.0.0
    azure-mgmt-recoveryservicesbackup==3.0.0
    azure-mgmt-notificationhubs==7.0.0
    azure-mgmt-eventhub==10.1.0
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    # Install kubectl and helm
    - |
      RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && \
        chmod +x ./kubectl && \ 
        mv ./kubectl /usr/local/bin/kubectl && \
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
        chmod +x get_helm.sh && \
        ./get_helm.sh
    # Install Google-cloud-cli 
    - |
      RUN echo "[google-cloud-cli]" > /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "name=Google Cloud CLI" >> /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64" >> /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "enabled=1" >> /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "gpgcheck=1" >> /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "repo_gpgcheck=0" >> /etc/yum.repos.d/google-cloud-sdk.repo && \
        echo "gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" >> /etc/yum.repos.d/google-cloud-sdk.repo
    - RUN yum install -y google-cloud-cli
    - RUN yum install -y google-cloud-cli-gke-gcloud-auth-plugin
