---
- name: Install MongoDB on GCP Instance ansible-mongo
  hosts: service_mongodb
  become: yes
  tasks:
    - name: Install gnupg and curl
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnupg
        - curl

    - name: Check if MongoDB GPG key and dearmor exists
      ansible.builtin.stat:
        path: "{{ mongo_user_keyrings_dir }}-{{ mongo_version }}.gpg"
      register: key_file_stat

    - name: Download MongoDB GPG key and dearmor
      ansible.builtin.shell: "{{ mongo_gpg_install }}"
      when: key_file_stat.stat.exists == False

    - name: Add MongoDB APT repository line
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/mongodb-org-{{ mongo_version }}.list
        line:  "{{ mongo_repository }}"
        create: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Create MongoDB data directory
      ansible.builtin.file:
        path: "{{ mongo_data_dir }}"
        state: directory
        owner: "{{ mongo_config_owner }}"
        group: "{{ mongo_config_group }}"
        mode: 0755

    - name: Install MongoDB tools
      ansible.builtin.apt:
        name: mongodb-database-tools
        state: present

    - name: Start MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
        