---
- name: Nexus
  hosts: service_nexus
  become: yes

  roles:
    - { role: geerlingguy.certbot }
    - { role: geerlingguy.apache, apache_create_vhosts: no, apache_mods_enabled: ["proxy", "proxy_http", "headers", "ssl", "rewrite"], apache_remove_default_vhost: true, tags: ['geerlingguy.apache'] }
    - { role: geerlingguy.java, java_packages: openjdk-8-jre-headless }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
