---
- name: Nexus
  hosts: service_nexus
  become: yes
  pre_tasks:
    - name: Retrive required for nexus secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ hashicorp_vault_server }}"
        auth_method: userpass
        username: "{{ hashicorp_vault_ansible_username }}"
        password: "{{ hashicorp_vault_ansible_password }}"
        engine_mount_point: "{{ hashicorp_vault_nexus_mount_point }}"
        path: "{{ hashicorp_vault_nexus_path }}"
      register: nexus_credentials
      no_log: true # Ensure not to log credentials
      delegate_to: localhost
      become: no

    - name: Extract nexus facts
      ansible.builtin.set_fact:
        nexus_public_hostname:     "{{ nexus_credentials.secret.public_hostname }}"
        nexus_admin_password:      "{{ nexus_credentials.secret.admin_password }}"
        nexus_jenkins_user:        "{{ nexus_credentials.secret.jenkins_username }}"
        nexus_jenkins_password:    "{{ nexus_credentials.secret.jenkins_password }}"
        nexus_kubernetes_user:     "{{ nexus_credentials.secret.kubernetes_username }}"
        nexus_kubernetes_password: "{{ nexus_credentials.secret.kubernetes_password }}"

    
    - name: Retrive required for certbot secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ hashicorp_vault_server }}"
        auth_method: userpass
        username: "{{ hashicorp_vault_ansible_username }}"
        password: "{{ hashicorp_vault_ansible_password }}"
        engine_mount_point: "{{ hashicorp_vault_certbot_mount_point }}"
        path: "{{ hashicorp_vault_certbot_path }}"
      register: certbot_credentials
      no_log: true # Ensure not to log credentials
      delegate_to: localhost
      become: no

    - name: Extract nexus facts
      ansible.builtin.set_fact:
        certbot_email: "{{ certbot_credentials.secret.email }}"

  roles:
    - { role: geerlingguy.certbot }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.java, java_packages: openjdk-8-jre-headless }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
