- name: Node exporter install
  hosts: all
  strategy: free
  become: yes
  tasks:
    - name: Run node exporter container
      community.docker.docker_container:
        name: "{{ node_exporter_container_name }}"
        image: "{{ node_exporter_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ node_exporter_port }}:9100"
        mounts:
          - type: bind
            source: /proc
            target: /host/proc:ro
          - type: bind
            source: /sys
            target: /host/sys:ro
          - type: bind
            source: /
            target: /rootfs:ro
        healthcheck:
          test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:9100 || exit 1"]
