---
- name: Patch GCP application approle secret
  hosts: localhost
  gather_facts: true # True to retrieve user home directory
  pre_tasks:
    - name: Activate service account
      ansible.builtin.shell: 
        cmd: |
          gcloud auth activate-service-account --key-file="${{ gcp_sa_env }}" --project "${{ gcp_project_env }}"
    
    - name: Generate kubeconfig to use kubeclt
      ansible.builtin.shell: 
        cmd: |
          gcloud container clusters get-credentials "{{ gcp_cluster_name }}" --zone "{{ gcp_cluster_zone }}" --project "${{ gcp_project_env }}"
      environment:
        KUBECONFIG: "{{ gcp_kubeconfig_path }}"

  roles:
    - { role: patch-app-vault-secret, k8s_kubeconfig_path: "{{ gcp_kubeconfig_path }}" }
