---
- name: Configure azure kubernetes cluster
  hosts: localhost
  gather_facts: true # True to retrieve user home directory
  pre_tasks:
    - name: Get kubeconfig for the cluster
      azure_rm_aks_info:
        auth_source: "{{ az_auth_source }}"
        resource_group: "{{ aks_cluster_rg }}"
        show_kubeconfig: "{{ az_extract_kubeconfig_type }}"
        tags: "{{ az_cluster_tags }}"
      register: aks_clusters

    - name: Extract cluster from the list
      ansible.builtin.set_fact:
        aks_cluster_kubeconfig: "{{ aks_clusters.aks | map(attribute='kube_config') | first }}"

    - name: Create kubeconfig file for the cluster
      copy:
        content: "{{ aks_cluster_kubeconfig }}"
        dest: "{{ az_kubeconfig_path }}"
        mode: "{{ az_kubeconfig_mode }}"

  roles:
    - { role: patch-app-vault-secret, k8s_kubeconfig_path: "{{ az_kubeconfig_path }}" }