---
- name: Postgres server
  hosts: localhost
  vars:
    postgres_host: "YOUR_POSTGRES_HOST"
    postgres_login_user: "YOUR_POSTGRES_USER"
    postgres_login_password: "YOUR_POSTGRES_PASSWORD"
    postgres_port: 5432
    postgres_admin_user: "YOUR_ADMIN_USER"
    postgres_admin_password: "YOUR_ADMIN_PASSWORD"
    postgres_schedule_database_name: schedule
    postgres_restore_dump: true
    postgres_initial_data_dest: "./files/initial_data.sql"
    postgre_admin_roles: "CREATEDB"
  tasks:
    - name: Create admin user
      community.postgresql.postgresql_user:
        login_host: "{{ postgres_host  }}"
        login_user: "{{ postgres_login_user  }}"
        login_password: "{{ postgres_login_password  }}"
        port: "{{ postgres_port  }}"
        name: "{{ postgres_admin_user }}"
        password: "{{ postgres_admin_password }}"
        role_attr_flags: "{{ postgre_admin_roles }}"

    - name: Create database
      community.postgresql.postgresql_db:
        login_host: "{{ postgres_host  }}"
        login_user: "{{ postgres_admin_user  }}"
        login_password: "{{ postgres_admin_password  }}"
        port: "{{ postgres_port  }}"
        name: "{{ postgres_schedule_database_name }}"
        owner: "{{ postgres_admin_user }}"
        state: present
        
    - name: Restore dump from stage and dev envirnoment
      community.postgresql.postgresql_db:        
        login_host: "{{ postgres_host  }}"
        login_user: "{{ postgres_admin_user  }}"
        login_password: "{{ postgres_admin_password  }}"
        name: "{{ postgres_schedule_database_name }}"
        state: restore
        target: "{{ postgres_initial_data_dest }}"
      when: postgres_restore_dump
      