- name: Redis server
  hosts: service_redis
  become: yes
  vars:
    redis_port: 6379
    redis_image: redis:alpine
  roles:
    - install_docker
  post_tasks:
    - name: Run redis container
      community.docker.docker_container:
        name: redis
        state: started
        image: "{{ redis_image }}"
        restart_policy: always
        published_ports:
          - "{{ redis_port }}:6379"
        mounts:
          - source: redis
            target: /root/redis
