- name: My play
  hosts: localhost
  connection: local 
  vars:
    postgres_ip: "11.11.11.11"
    postgres_port: "5432"
  tasks:
    # - name: Read variables
    #   ansible.builtin.debug:
    #     msg: "ansible_connection: {{ docker_dir }};node_exporter_image: {{node_exporter_image}}"
    - name: show templating results
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', './templates/prometheus_default.j2') }}"
