# - name: My play
#   hosts: localhost
#   connection: local 
#   vars:
#     postgres_ip: "11.11.11.11"
#     postgres_port: "5432"
#   tasks:
#     # - name: Read variables
#     #   ansible.builtin.debug:
#     #     msg: "ansible_connection: {{ docker_dir }};node_exporter_image: {{node_exporter_image}}"
#     - name: show templating results
#       ansible.builtin.debug:
#         msg: "{{ lookup('ansible.builtin.template', './templates/prometheus_default.j2') }}"

# - name: Print all hosts
#   hosts: all
#   tasks:
#     - name: Print all  hosts ips
#       ansible.builtin.debug:
#         var: hostvars[item]['ansible_default_ipv4']['address']
#       with_items: "{{ groups['all'] }}"

- name: Print all hosts
  hosts: service_grafana
  tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['private_ip'] is not defined
      with_items: "{{ groups['all'] }}"
    - name: Print prometheus config file
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', './templates/prometheus_default.j2') }}"
    - name: Set useful facts
      set_fact:
        postgres_ip: "{{ hostvars[groups['service_postgres'] | first]['private_ip'] }}"
        redis_ip: "{{ hostvars[groups['service_redis'] | first]['private_ip'] }}"
        mongo_url: "{{ hostvars[groups['service_mongo'] | first]['private_ip']}}"
    - name: Debug facts
      ansible.builtin.debug:
        msg: "postgres_ip: {{ postgres_ip }}, redis_ip: {{ redis_ip }}, mongo_url: {{ mongo_url }}"

      