# - name: My play
#   hosts: localhost
#   connection: local 
#   vars:
#     postgres_ip: "11.11.11.11"
#     postgres_port: "5432"
#   tasks:
#     # - name: Read variables
#     #   ansible.builtin.debug:
#     #     msg: "ansible_connection: {{ docker_dir }};node_exporter_image: {{node_exporter_image}}"
#     - name: show templating results
#       ansible.builtin.debug:
#         msg: "{{ lookup('ansible.builtin.template', './templates/prometheus_default.j2') }}"

- name: Print all hosts
  hosts: all
  tasks:
    - name: Print all  hosts ips
      ansible.builtin.debug:
        var: hostvars[item]['ansible_default_ipv4']['address']
      with_items: "{{ groups['all'] }}"
