---
- name: Create keyrings directory if not exists
  file:
    path: "{{ keyrings_dir }}"
    state: directory
    mode: "{{ keyrings_dir_mode }}"

- name: Download Docker gpg key
  get_url:
    url: "{{ docker_gpg_url }}"
    dest: "{{ keyring_armored_docker_file }}"
    mode: "{{ keyring_file_mode }}"

- name: De-Armor Docker GPG key
  command:  gpg --dearmor -o "{{ keyring_docker_file }}" "{{ keyring_armored_docker_file }}"
  args:
    creates: "{{ keyring_docker_file }}"

- name: Set permissions for Docker GPG key
  file:
    path: "{{ keyring_docker_file }}"
    mode: "{{ keyring_file_mode }}"

- name: Add Docker repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
  notify: Update Apt cache
