---
# defaults file for patch-app-vault-secret
k8s_kubeconfig_path: "PATH_TO_KUBECONFIG"


hashicorp_vault_server: "YOUR_HASHICORP_VAULT_SERVER_ADDRESS"
hashicorp_vault_ansible_username: "YOUR_ANSIBLE_USERNAME"
hashicorp_vault_ansible_password: "YOUR_ANSIBLE_PASSWORD"


schedule_app_namespace: "YOUR_APPLICATION_NAMESPACE"

schedule_app_hashicorp_approle_secret_name: "YOUR_K8S_APPROLE_SECRET_NAME"
hashicorp_vault_approle_application_secret_id_path: "YOUR_APPROLE_SECRET_PATH"
schedule_app_secret_patch_definition:
  data:
    secret-id: "{{ hashicorp_vault_approle_application_secret_id | b64encode }}"
