---
- name: Add mesh proxy default
  kubernetes.core.k8s:
    kubeconfig: "{{ item.kubeconfig_path }}"
    state: present
    namespace: "{{ consul_namespace }}"
    definition: "{{ lookup('ansible.builtin.template', 'templates/proxy-default.yaml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
  loop: "{{ datacenters }}"
