---
# Global
envirnoment: dev

# Kuberntenes config context
k8s_kubeconfig_path: "$HOME/.kube/config"

# Git
k8s_repo: "https://github.com/BlueTeam2/class-schedule-k8s.git"
k8s_clone_repo: /tmp/k8s_class_schedule_chart

# Application
schedule_app_namespace: schedule-app
schedule_app_backend_name: backend
schedule_app_backend_image_name: class-schedule-backend
schedule_app_backend_image_tag: latest

schedule_app_frontend_name: frontend
schedule_app_frontend_image_name: class-schedule-frontend
schedule_app_frontend_image_tag: latest

schedule_app_backend_force_update: false
schedule_app_frontend_force_update: false

# Vault
hashicorp_vault_server: "YOUR_HASHICORP_VAULT_SERVER"

hashicorp_vault_ansible_username: "YOUR_ANSIBLE_USERNAME"
hashicorp_vault_ansible_password: "YOUR_ANSIBLE_PASSWORD"

hashicorp_vault_approle_application_role_id_path: "auth/approle/role/app_{{ envirnoment }}/role-id"
hashicorp_vault_approle_application_secret_id_path: "auth/approle/role/app_{{ envirnoment }}/secret-id"

# Consul
consul_dc_name: dc1
