plugin: google.cloud.gcp_compute
projects:
  - softseve-blue-team
service_account_file: ./keys/softseve-blue-team.json
auth_kind: serviceaccount
keyed_groups:
  - key: labels.env
    prefix: env
  - key: labels.service
    prefix: service
hostnames:
  # List hosts by name instead of the default public IP
  - name
  - public_ip
  - private_ip
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  private_ip: networkInterfaces[0].networkIP