---
- name: Add external-secrets repository
  kubernetes.core.helm_repository:
    repo_name: "{{ es_repo_name }}"
    repo_url: "{{ es_repo_url }}"

- name: Deploy external-secrets chart
  kubernetes.core.helm:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    chart_ref: "{{ es_repo_name }}/{{ es_chart_name }}"
    create_namespace: true
    release_namespace: "{{ es_namespace }}"
    release_name: "{{ es_release_name }}"
    set_values: "{{ es_overwrite_values }}"

- name: Wait for external-secrets to be running
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    kind: "{{ es_is_ready.service_kind }}"
    namespace: "{{ es_namespace }}"
    name: "{{ es_is_ready.service_name }}"
    wait: true
    wait_condition: "{{ es_is_ready.wait_condition }}"
