---
- name: Retrieve application approle role-id
  community.hashi_vault.vault_read:
    url: "{{ hashicorp_vault_server }}"
    auth_method: userpass
    username: "{{ hashicorp_vault_ansible_username }}"
    password: "{{ hashicorp_vault_ansible_password }}"
    path: "{{ hashicorp_vault_approle_application_role_id_path }}"
  register: app_approle_id

- name: Retrieve application approle secret-id
  community.hashi_vault.vault_write:
    url: "{{ hashicorp_vault_server }}"
    auth_method: userpass
    username: "{{ hashicorp_vault_ansible_username }}"
    password: "{{ hashicorp_vault_ansible_password }}"
    path: "{{ hashicorp_vault_approle_application_secret_id_path }}"
  register: app_secret_id

- name: Retrive nexus credentials form the vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ hashicorp_vault_server }}"
    auth_method: "userpass"
    username: "{{ hashicorp_vault_ansible_username }}"
    password: "{{ hashicorp_vault_ansible_password }}"
    engine_mount_point: "{{ hashicorp_vault_nexus_mount_point }}"
    path: "{{ hashicorp_vault_nexus_path }}"
  register: nexus_credentials
    
- name: Set necessary variables
  ansible.builtin.set_fact:
    hashicorp_vault_approle_application_role_id: "{{ app_approle_id.data.data.role_id }}"
    hashicorp_vault_approle_application_secret_id: "{{ app_secret_id.data.data.secret_id }}"
    nexus_public_hostname: "{{ nexus_credentials.secret.public_hostname }}"
    nexus_kubernetes_user: "{{ nexus_credentials.secret.kubernetes_username }}"
    nexus_kubernetes_password: "{{ nexus_credentials.secret.kubernetes_password }}"
