---
- name: Retrieve vault approle secret-id
  community.hashi_vault.vault_write:
    url: "{{ hashicorp_vault_server }}"
    auth_method: userpass
    username: "{{ hashicorp_vault_ansible_username }}"
    password: "{{ hashicorp_vault_ansible_password }}"
    path: "{{ hashicorp_vault_approle_application_secret_id_path }}"
  register: app_secret_id
  no_log: true # Ensure not to log credentials

- name: Set necessary variables
  ansible.builtin.set_fact:
    hashicorp_vault_approle_application_secret_id: "{{ app_secret_id.data.data.secret_id }}"
  no_log: true # Ensure not to log credentials

- name: Patch kubernetes approle token secret
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: patched
    kind: secret
    namespace: "{{ schedule_app_namespace }}"
    name: "{{ schedule_app_hashicorp_approle_secret_name }}"
    definition: "{{ schedule_app_secret_patch_definition }}"
