---
# vars file for install_docker
required_packages:
  - ca-certificates
  - curl
  - gnupg
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
keyrings_dir: '/etc/apt/keyrings'
keyring_docker_file: "{{ keyrings_dir }}/docker.gpg"
keyring_armored_docker_file: "{{ keyrings_dir }}/docker.gpg_armored"
keyrings_dir_mode: '0755'
keyring_file_mode: '0755'
