---
# GCP configuration
gcp_sa_env: GCP_SERVICE_ACCOUNT_FILE
gcp_project_env: GCP_PROJECT
cluster_name: stage-schedule
cluster_zone: us-central1-b

# Application
schedule_app_namespace: schedule-app

# Patch vault secret to renew token
schedule_app_hashicorp_approle_secret_name: hashicorp-vault-approle-token
schedule_app_secret_patch_definition:
  data:
    secret-id: "{{ hashicorp_vault_approle_application_secret_id | b64encode }}"

# Postgres configuration
postgres_port: 5432
postgres_schedule_database_name: schedule
postgres_restore_dump: true
postgres_initial_data_dest: "./files/initial_data.sql"
postgre_admin_roles: "CREATEDB"
