---
# Global
k8s_kubeconfig_base_path: "{{ ansible_env.HOME }}/.kube"

# GCP configuration
gcp_sa_env: GCP_SERVICE_ACCOUNT_FILE
gcp_project_env: GCP_PROJECT
gcp_kubeconfig_env: KUBECONFIG
gcp_kubeconfig_path: "{{ k8s_kubeconfig_base_path }}/gcp_config"
gcp_conul_dc_name: gcp
gcp_cluster_name: "{{ app_env }}-schedule"
gcp_cluster_zone: us-central1-b

# Azure configuraion
az_kubeconfig_path: "{{ k8s_kubeconfig_base_path }}/az_config"
az_kubeconfig_mode: "0644"
az_extract_kubeconfig_type: "admin"
az_auth_source: "env"
aks_cluster_rg: "{{ app_env }}-schedule"
aks_conul_dc_name: aks
az_cluster_tags:
  - "env:{{ app_env }}"
  - "app:schedule"


# Application
schedule_app_namespace: schedule-app

# Patch vault secret to renew token
schedule_app_hashicorp_approle_secret_name: hashicorp-vault-approle-token

# Postgres configuration
postgres_port: 5432
postgres_schedule_database_name: schedule
postgres_initial_data_dest: "./files/initial_data.sql"
postgre_admin_roles: "CREATEDB"
